services:
  iceberg-rest:
    image: tabulario/iceberg-rest:latest
    container_name: whoop-iceberg-rest
    ports:
      - "8181:8181"
    environment:
      CATALOG_WAREHOUSE: s3://whoop-lakehouse/iceberg
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
      S3_ENDPOINT: http://host.docker.internal:9000
      S3_PATH_STYLE_ACCESS: "true"

  trino:
    image: trinodb/trino:452
    container_name: whoop-trino
    ports:
      - "8080:8080"
    volumes:
      - ./catalog:/etc/trino/catalog
    environment:
      - TZ=America/Los_Angeles
    depends_on:
      - iceberg-rest