services:
  minio:
    image: minio/minio:latest
    container_name: whoop-minio
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - whoop_minio_data:/data

  postgres:
    image: postgres:14  # Use 14 instead of 15
    container_name: whoop-postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"  # Force MD5 at init
    ports:
      - "5433:5432"
    volumes:
      - whoop_pg_data:/var/lib/postgresql/data

  hive-metastore:
    image: apache/hive:3.1.3
    platform: linux/amd64
    container_name: whoop-hive-metastore
    depends_on:
      - postgres
      - minio
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      IS_RESUME: "true" 
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://whoop-postgres:5432/metastore
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive
        -Dhive.metastore.warehouse.dir=s3a://whoop-lakehouse/warehouse
        -Dfs.s3a.endpoint=http://whoop-minio:9000
        -Dfs.s3a.access.key=minioadmin
        -Dfs.s3a.secret.key=minioadmin
        -Dfs.s3a.path.style.access=true
        -Dfs.s3a.connection.ssl.enabled=false
        -Dfs.s3a.endpoint.region=us-east-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9083"]
      interval: 10s
      timeout: 5s
      retries: 5


  trino:
    image: trinodb/trino:452
    container_name: whoop-trino
    ports:
      - "8080:8080"
    volumes:
      - ./catalog:/etc/trino/catalog
    environment:
      - TZ=America/Los_Angeles
    depends_on:
      - hive-metastore
      - minio
volumes:
  whoop_minio_data:
  whoop_pg_data:
  